apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kratos-template-bff
  namespace: kratos-template-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
spec:
  tls:
    - hosts:
        - kratos-template-bff-dev.camera360.com
      secretName: camera360.com
  rules:
    - host: kratos-template-bff-dev.camera360.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: kratos-template-bff
                port:
                  number: 8000
