apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-template
  name: template-bff
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
spec:
  tls:
    - hosts:
        - template-bff-dev.template.com
      secretName: template.com
  rules:
    - host: template-bff-dev.template.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: template-bff
                port:
                  number: 8000
