apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-April
  name: April-bff
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
spec:
  tls:
    - hosts:
        - April-bff-dev.April.com
      secretName: April.com
  rules:
    - host: April-bff-dev.April.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: April-bff
                port:
                  number: 8000
