apiVersion: v1
kind: Service
metadata:
  namespace: app-template
  name: template-bff
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "9000"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: template-bff
