// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/pinguo-icc/template/internal/application"
	"github.com/pinguo-icc/template/internal/infrastructure/clientset"
	"github.com/pinguo-icc/template/internal/infrastructure/conf"
	"github.com/pinguo-icc/template/internal/infrastructure/server"
)

// Injectors from wire.go:

func initApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	http := bootstrap.Http
	params := bootstrap.Params
	clientSet, cleanup, err := clientset.NewClientSet(params, logger)
	if err != nil {
		return nil, nil, err
	}
	example := &application.Example{
		ClientSet: clientSet,
	}
	routerDefines := &application.RouterDefines{
		E: example,
	}
	httpServer, cleanup2 := server.NewHttpServer(http, logger, routerDefines)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
