app:
    env: &appEnv qa
trace:
    level: debug
    env: *appEnv
    jaeger:
        endpoint: http://10.0.5.176:14268/api/traces
qiniu:
    accessKey: IAM-Ej1TW2KrVqRIOkIqZVEPta_yLmnUc8-1LySvtWCb
    secretKey: vLw21BLiVx75oqMzbb3To1C1L6Tajtb7m7bRVpOK_4MF
    bucket: qa-c360
    url: https://cdn-qa-all.c360dn.com
    isPrivate: false
recorder:
  filePath: /opt/logs/camera360.log
  maxSize: 100
  maxAge: 1
  maxBackups: 5