app:
    env: &appEnv dev
clientSet:
    fieldDef: dns:///192.168.1.233:32266
    operationalPos: dns:///192.168.1.233:31250
    material: dns:///localhost:9004
    operationalBasicSvcAddr: dns:///localhost:9000
trace:
    level: debug
    env: *appEnv
    jaeger:
        endpoint: http://192.168.1.233:31358/api/traces
qiniu:
    accessKey: IAM-Ej1TW2KrVqRIOkIqZVEPta_yLmnUc8-1LySvtWCb
    secretKey: vLw21BLiVx75oqMzbb3To1C1L6Tajtb7m7bRVpOK_4MF
    bucket: qa-c360
    url: https://cdn-qa-all.c360dn.com
    isPrivate: false
