app:
    name: &appName camera360-bff
    env: &appEnv prod
http:
    address: 0.0.0.0:8000
    timeout: 30s
trace:
    name: *appName
    env: *appEnv
    level: prod
    jaeger:
        endpoint: http://10.0.5.176:14268/api/traces
    aliConfig:
        project: ""
        instanceId: ""
        endpoint: ""
        accessKey: ""
        accessSecret: ""
qiniu:
    accessKey: ""
    secretKey: ""
    bucket: operations-placing-system
    url: https://ops.c360dn.com
    isPrivate: false
clientSet:
    fieldDef: dns:///field-definitions.operation-placing-system:9000
    operationalPos: dns:///operational-positions.operation-placing-system:9000
    material: dns:///operations-materials.operation-placing-system:9000
params:
