apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: template-bff-hpa-v1
  namespace: app-template
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: template-bff
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80