apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camera360-bff-hpa-v1
  namespace: app-camera360
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80