apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: april-bff-hpa-v1
  namespace: app-april
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: april-bff
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80