apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-camera360
  name: camera360-bff
spec:
  rules:
    - host: camera360-bff-k8s.camera360.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: camera360-bff
                port:
                  number: 8000
