apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-template
  name: template-bff
spec:
  rules:
    - host: template-bff-k8s.template.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: template-bff
                port:
                  number: 8000
