apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml
  - svc.yaml

patches:
  - path: deploy-patch.yaml
    target:
      Kind: Deployment
