apiVersion: v1
kind: Service
metadata:
  name: template-bff-pprof
  namespace: app-template
spec:
  type: NodePort
  ports:
    - name: pprof
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: template-bff
