apiVersion: v1
kind: Service
metadata:
  name: camera360-bff-pprof
  namespace: app-camera360
spec:
  type: NodePort
  ports:
    - name: pprof
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: camera360-bff
